### PR TITLE
Corrected down_message to down_msg.

### PR DESCRIPTION
**Pull request by robdesbois**

### CODE REVIEW

**Comment by Neverlord** [comment]
Thanks! 👍

**Comment by robdesbois** [comment]
No worries Dominik, thanks for the excellent framework (+ papers, docs & videos) - we've just started building a new concurrent, distributable system on top of it after some exciting prototyping :smiley:

**Comment by Neverlord** [comment]
That's awesome. Can you share anything more specific about your project at this point? Maybe per private mail if you don't want to go public right now. :)

**Comment by robdesbois** [comment]
Cool - sent you a mail separately.

**Pull request merged**
